BDD_module_solution
yauhenFan/advanced pull request #5
Opened 2024-12-29 15:42 UTC by yauhenFan

Hi @Dashnik,

Could you review the following MR?

Changes:

1. BDD framework implemented:
![image](https://github.com/user-attachments/assets/3adc6dd1-8620-42c6-9033-4013f6358ad2)
2. Cucumber framework with wdio installed:
![image](https://github.com/user-attachments/assets/7c9dd696-0363-4a1f-a2cc-7bbd12fafab1)
3. After hook implemented:
![image](https://github.com/user-attachments/assets/d589ec28-07e1-4164-952d-4fb5e427535e)
4. 'Background' keywork implemented:
![image](https://github.com/user-attachments/assets/31083a96-6ab6-4af9-a22e-b7b6939e126c)
5. Scenario Outline implemented:
![image](https://github.com/user-attachments/assets/43a61880-112d-46ab-9a42-5956793d738d)
6. Parallelization implemented:
![image](https://github.com/user-attachments/assets/d351854c-5dd3-4d1f-a484-081cf9016ba9)

2025-01-02 07:55 UTC, yauhenFan commented
gitHub actions implemented and status us 'Green':
![image](https://github.com/user-attachments/assets/fd810ac8-44ad-42ea-898a-6fa9ae762f7b)

2025-01-26 19:25 UTC, Dashnik requested changes

2025-01-26 19:25 UTC, Dashnik commented on .github/workflows/ci.yml
Need to add step which will launch tests

2025-01-26 19:25 UTC, Dashnik commented on BDD/src/data/url.js
In the homework assignment, it is not explicitly stated how to incorporate the BDD approach into the project. Therefore, the option of adding a BDD folder is quite reasonable, but the problem is that it leads to a lot of duplicate code, which worsens the readability and structure of the code and duplicates many files unnecessarily. Let’s unify this aspect and remove all duplicates, at the very least.

2025-01-26 19:25 UTC, Dashnik commented on BDD/src/features/createDashboard.feature
> +When I login with default User credentials 'default' and '1q2w3e'
It's strictly forbidden to commit credentials to the source control version.

2025-01-26 19:25 UTC, Dashnik commented on BDD/src/features/createDashboard.feature
> +Scenario: User logs in with default credentials
From my point of view,  it's better to use the Background keyword instead of the Scenario keyword. 
A Scenario is an individual test case that specifies a particular behavior or outcome to be validated, while a Background is a shared context or setup that prepares the environment for multiple scenarios to execute in a consistent state.

2025-01-26 19:25 UTC, Dashnik commented on BDD/src/features/createDashboard.feature
> +Given I open web site 'http://localhost:8080/ui/#login'
If the domain or path changes at any moment, you will need to refactor all existing cases that use the changed URL for everyone. I believe it is better to create a constant and export it for every test. This way, when the URL changes, it will only be necessary to update it in one place.

2025-01-26 19:25 UTC, Dashnik commented on BDD/src/step-definitions/steps.js
> +			await dashboardPage.addDashboardModalWindow.isDisplayed()
It's not necessary to overcomplicate things here. Instead of using the long-form `await expect(await dashboardPage.addDashboardModalWindow.isDisplayed()).toEqual(true);,` you could write it more concisely as `await expect(dashboardPage.addDashboardModalWindow).toBeDisplayed().` I’d recommend applying this approach to all assertions to make the code cleaner and simpler.

2025-01-26 19:25 UTC, Dashnik commented on BDD/src/step-definitions/steps.js
> +Given('I open web site {string}', async page => {
page isn't a meaningful name in this context. It's better to use something more descriptive, like pageUrl

2025-01-30 18:31 UTC, Dashnik approved these changes

2025-01-30 18:31 UTC, merged